name: Lint

on:
    push:
        branches:
            - master
            - dev

jobs:
    golangci:
        strategy:
            matrix:
                go-version: [ 1.14.x, 1.16.x ]
                platform: [ windows-latest, ubuntu-latest, macos-latest ]

        runs-on: ${{ matrix.platform }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: golangci-lint
                uses: golangci/golangci-lint-action@v2
                with:
                    version: v1.41.1
