name: Lint

on:
    push:
        branches:
            - master

jobs:
    lint:
        strategy:
            matrix:
                go-version: [ 1.15 ]
                platform: [ windows-latest, ubuntu-latest, macos-latest ]

        runs-on: ${{ matrix.platform }}

        steps:
            -   name: Install Go
                uses: actions/setup-go@v2
                with:
                    go-version: ${{ matrix.go-version }}

            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Lint
                run: |
                    curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.36.0
                    golangci-lint run
