name: Test

on:
    push:
        branches:
            - master

jobs:
    test:
        strategy:
            matrix:
                go-version: [ 1.16 ]
                platform: [ windows-latest, ubuntu-latest, macos-latest ]

        runs-on: ${{ matrix.platform }}

        steps:
            -   name: Install Go
                uses: actions/setup-go@v2
                with:
                    go-version: ${{ matrix.go-version }}

            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Test and generate coverage report
                run: |
                    go test ./... -timeout 20m -race -coverprofile=coverage.txt -covermode=atomic

            -   name: LS Info
                run: |
                    ls -la

            -   name: Upload coverage to codecov
                uses: codecov/codecov-action@v1
                with:
                    file: ./coverage.txt
                    flags: unittests
                    fail_ci_if_error: true
